services:
  customizer_service:
    build:
      dockerfile: ./Dockerfile
    environment:
      - WEBSTORE_PG_URL=jdbc:postgresql://localhost:6432/webstore
      - WEBSTORE_PG_USER=user
      - WEBSTORE_PG_PASS=password
    ports:
      - "8089:8089"